version: "3"
services: 
    app:
        container_name: game_service
        build: .
        depends_on: 
            - mongo
        ports:
            - "8000:8080"
        links: 
            - mongo
    mongo:
        container_name: mongo
        image: mongo
        ports: 
            - "27017:27017"
        volumes: 
            - /var/lib/mongodb:/data/db
